_prefs: 
  baselayer: ''
  mapid: afiedler.e83d82a2
  print: true
  saveCenter: false
_properties: {}
attribution: "<a href='https://www.mapbox.com/about/maps/' target='_blank'>&copy; Mapbox &copy; OpenStreetMap</a> <a class='mapbox-improve-map' href='https://www.mapbox.com/map-feedback/' target='_blank'>Improve this map</a>"
bounds: 
  - -180
  - -85.0511
  - 180
  - 85.0511
center: 
  - 0
  - 20
  - 2
description: ''
format: "png8:m=h"
interactivity_layer: ''
layers: 
  - landcover
  - landuse
  - contour.line
  - hillshade
  - waterway
  - water
  - aeroway
  - barrier_line
  - building
  - landuse_overlay
  - tunnel
  - road
  - bridge
  - admin
  - country_label_line
  - country_label
  - marine_label
  - state_label
  - place_label
  - water_label
  - poi_label
  - road_label
  - waterway_label
  - housenum_label
  - contour.label
maxzoom: 21
minzoom: 0
name: Hiking Map
source: "mapbox:///mapbox.mapbox-terrain-v2,mapbox.mapbox-streets-v5"
styles: 
  - style.mss
  - road.mss
  - label.mss
  - poi.mss
template: ''
